# This file was generated by GoReleaser. DO NOT EDIT.
cask "cairn" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "958b58af271a5bda71fe6f8c9e7a330cb433cd3c4921e28e529a9a933fb84200"
      url "https://github.com/louisguitton/cairn/releases/download/v#{version}/cairn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f096abffafc9772d4bc8920e9535780da339bfbe1259bdc11b9ad9d2493274c"
      url "https://github.com/louisguitton/cairn/releases/download/v#{version}/cairn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7639e5c4b5fc5dabfa8a864ae60daf417713c4543f1c2bf18fbeb613e3b169ae"
      url "https://github.com/louisguitton/cairn/releases/download/v#{version}/cairn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd84f3e74fb5e357e161a253daf5dd3cc9acc6dbd02e8a024ebca9944e425e3f"
      url "https://github.com/louisguitton/cairn/releases/download/v#{version}/cairn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cairn"
  desc "Prompt-driven Product Design Thinking kit on the IBM EDT Loop"
  homepage "https://github.com/louisguitton/cairn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cairn"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cairn"]
    end
  end

  # No zap stanza required

end
