# This file was generated by GoReleaser. DO NOT EDIT.
cask "cairn" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "108f2c8baa07d753757f2945048de85d9d72d32f2f206d7794ccd599e78c35aa"
      url "https://github.com/louisguitton/cairn/releases/download/v#{version}/cairn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c00cf70a065196fc60caa60a60e4554f13824fee5bdfc79c511d2890995b5d8e"
      url "https://github.com/louisguitton/cairn/releases/download/v#{version}/cairn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "36b1d3968dd1188117780dd202dfaa2a8aa24673fd4dcdcebb01ec66f92ab31f"
      url "https://github.com/louisguitton/cairn/releases/download/v#{version}/cairn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "898d1b694203dd9c66ff8ec71c5044dedd6f09b9b75599211a0aca0e736521e2"
      url "https://github.com/louisguitton/cairn/releases/download/v#{version}/cairn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cairn"
  desc "Prompt-driven Product Design Thinking kit on the IBM EDT Loop"
  homepage "https://github.com/louisguitton/cairn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cairn"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cairn"]
    end
  end

  # No zap stanza required

end
