# This file was generated by GoReleaser. DO NOT EDIT.
cask "cairn" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "3f7ce2a37880c096c670d9d671523b30776a85ac6507b5aa497cabb00e423cf8"
      url "https://github.com/louisguitton/cairn/releases/download/v#{version}/cairn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "afc6a9a62c62adda36b799fa898d0782e98990535cf6b4a34d54efb903deca15"
      url "https://github.com/louisguitton/cairn/releases/download/v#{version}/cairn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d950348496834648f363c48677eb640d4532d2c8bc0806a2374a9816f3160c67"
      url "https://github.com/louisguitton/cairn/releases/download/v#{version}/cairn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "42b63fec9d23e31e2904ee9964cdf5e91b60c8fa770dec141089f422e5058049"
      url "https://github.com/louisguitton/cairn/releases/download/v#{version}/cairn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cairn"
  desc "Prompt-driven Product Design Thinking kit on the IBM EDT Loop"
  homepage "https://github.com/louisguitton/cairn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cairn"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cairn"]
    end
  end

  # No zap stanza required

end
